# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - useflaskdocker02

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_82dfd8f94f1b4f7e86ee1e465d741b31 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_288645a7d91d4263b8c4726933b8c476 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_82dfd8f94f1b4f7e86ee1e465d741b31 }}/3.8-slim-buster:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'useflaskdocker02'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c887e409aacf4146a68dc5a935a5898c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_82dfd8f94f1b4f7e86ee1e465d741b31 }}/3.8-slim-buster:${{ github.sha }}'